/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Kafka Swing");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(500,500);
        JButton button = new JButton("Press");
        frame.getContentPane().add(new ConnectionsPanel()); // Adds Button to content pane of frame
        frame.setVisible(true);
    }
}
