/*
 * This source file was generated by the Gradle 'init' task
 */
package ua.com.abakumov.kafkaswing;

import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Kafka Swing");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(900,700);
            ConnectionsPanel connectionsPanel = new ConnectionsPanel(frame);
            connectionsPanel.drawYourself();
            frame.setVisible(true);
        });

    }
}
